### ISSUE TITLE
firefox快炸了(

### ISSUE THREAD

**Issue by BC204** [Ts-Final/Ts-Final.github.io#1]
盲猜是由于自动保存过于频繁，以致占用过多缓存

![截图 2024-03-21 11-13-15](https://github.com/Ts-Final/Ts-Final.github.io/assets/109511245/000989c7-28b3-4e59-9269-4003d46a5b44)

**Comment by BC204** [comment]
~~好吧，并不~~
似乎只在至少一项资源被生产时，才会触发

**Comment by Ts-Final** [comment]
后面会加上修改帧率的设置，现在设置的是33ms更新一次画面但是显然用不着
然后还有一种可能是顶栏的东西出了bug但是我忘记修了，会导致1min左右之后没有东西可以展示而无限递归
